log:
    stdout: true
    level: {{ default .Env.LOG_LEVEL "info" }}

persistence:
    numHistoryShards: {{ default .Env.NUM_HISTORY_SHARDS "4" }}
    defaultStore: default
    visibilityStore: visibility
    {{- $es := default .Env.ENABLE_ES "false" | lower -}}
    {{- if eq $es "true" }}
    advancedVisibilityStore: es-visibility
    {{- end }}
    datastores:
        {{- $db := default .Env.DB "cassandra" | lower -}}
        {{- if or (eq $db "cassandra") (eq $db "scylla") }}
        default:
            cassandra:
                hosts: {{ default .Env.CASSANDRA_SEEDS "" }}
                keyspace: {{ default .Env.KEYSPACE "cadence" }}
                user: {{ default .Env.CASSANDRA_USER "" }}
                password: {{ default .Env.CASSANDRA_PASSWORD "" }}
        visibility:
            cassandra:
                hosts: {{ default .Env.CASSANDRA_SEEDS "" }}
                keyspace: {{ default .Env.VISIBILITY_KEYSPACE "cadence_visibility" }}
                user: {{ default .Env.CASSANDRA_USER "" }}
                password: {{ default .Env.CASSANDRA_PASSWORD "" }}
        {{- else if eq $db "mysql" }}
        default:
            sql:
                pluginName: "mysql"
                databaseName: {{ default .Env.DBNAME "cadence" }}
                connectAddr: "{{ default .Env.MYSQL_SEEDS "" }}:{{ default .Env.DB_PORT "3306" }}"
                connectProtocol: "tcp"
                user: {{ default .Env.MYSQL_USER "" }}
                password: {{ default .Env.MYSQL_PWD "" }}
                {{- if .Env.MYSQL_TX_ISOLATION_COMPAT }}
                connectAttributes:
                    tx_isolation: 'READ-COMMITTED'
                {{- end }}
        visibility:
            sql:
                pluginName: "mysql"
                databaseName: {{ default .Env.VISIBILITY_DBNAME "cadence_visibility" }}
                connectAddr: "{{ default .Env.MYSQL_SEEDS "" }}:{{ default .Env.DB_PORT "3306" }}"
                connectProtocol: "tcp"
                user: {{ default .Env.MYSQL_USER "" }}
                password: {{ default .Env.MYSQL_PWD "" }}
                {{- if .Env.MYSQL_TX_ISOLATION_COMPAT }}
                connectAttributes:
                    tx_isolation: 'READ-COMMITTED'
                {{- end }}
        {{- else if eq $db "postgres" }}
        default:
            sql:
                pluginName: "postgres"
                encodingType: "thriftrw"
                decodingTypes: ["thriftrw"]
                databaseName: {{ default .Env.DBNAME "cadence" }}
                connectAddr: "{{ default .Env.POSTGRES_SEEDS "" }}:{{ default .Env.DB_PORT "5432" }}"
                connectProtocol: "tcp"
                user: {{ default .Env.POSTGRES_USER "" }}
                password: {{ default .Env.POSTGRES_PWD "" }}
                maxConns: 20
                maxIdleConns: 20
                maxConnLifetime: "1h"
        visibility:
            sql:
                pluginName: "postgres"
                encodingType: "thriftrw"
                decodingTypes: ["thriftrw"]
                databaseName: {{ default .Env.VISIBILITY_DBNAME "cadence_visibility" }}
                connectAddr: "{{ default .Env.POSTGRES_SEEDS "" }}:{{ default .Env.DB_PORT "5432" }}"
                connectProtocol: "tcp"
                user: {{ default .Env.POSTGRES_USER "" }}
                password: {{ default .Env.POSTGRES_PWD "" }}
                maxConns: 20
                maxIdleConns: 20
                maxConnLifetime: "1h"
        {{- end }}
        {{- if eq $es "true" }}
        es-visibility:
            elasticsearch:
                version: {{ default .Env.ES_VERSION "" }}
                username: {{ default .Env.ES_USER "" }}
                password: {{ default .Env.ES_PWD "" }}
                url:
                    scheme: "http"
                    host: "{{ default .Env.ES_SEEDS "" }}:9200"
                indices:
                    visibility: cadence-visibility-dev
        {{- end }}

ringpop:
    name: cadence
    bootstrapMode: {{ default .Env.RINGPOP_BOOTSTRAP_MODE "hosts" }}
    {{- if .Env.RINGPOP_SEEDS }}
    bootstrapHosts:
    {{- range $seed := (split .Env.RINGPOP_SEEDS ",") }}
        - {{ . }}
    {{- end }}
    {{- else }}
    bootstrapHosts:
        - {{ .Env.HOST_IP }}:7933
        - {{ .Env.HOST_IP }}:7934
        - {{ .Env.HOST_IP }}:7935
        - {{ .Env.HOST_IP }}:7939
    {{- end }}
    maxJoinDuration: 30s

services:
    frontend:
        rpc:
            port: 7933
            bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
        {{- if .Env.STATSD_ENDPOINT }}
        metrics:
            statsd:
                hostPort: {{ .Env.STATSD_ENDPOINT }}
                prefix: "cadence-frontend"
        {{- else if .Env.PROMETHEUS_ENDPOINT }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
        {{- else if .Env.PROMETHEUS_ENDPOINT_0 }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_0 }}
        {{- end }}

    matching:
        rpc:
            port: 7935
            bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
        {{- if .Env.STATSD_ENDPOINT }}
        metrics:
            statsd:
                hostPort: {{ .Env.STATSD_ENDPOINT }}
                prefix: "cadence-matching"
        {{- else if .Env.PROMETHEUS_ENDPOINT }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
        {{- else if .Env.PROMETHEUS_ENDPOINT_1 }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_1 }}
        {{- end }}

    history:
        rpc:
            port: 7934
            bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
        {{- if .Env.STATSD_ENDPOINT }}
        metrics:
            statsd:
                hostPort: {{ .Env.STATSD_ENDPOINT }}
                prefix: "cadence-history"
        {{- else if .Env.PROMETHEUS_ENDPOINT }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
        {{- else if .Env.PROMETHEUS_ENDPOINT_2 }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_2 }}
        {{- end }}

    worker:
        rpc:
            port: 7939
            bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
        {{- if .Env.STATSD_ENDPOINT }}
        metrics:
            statsd:
                hostPort: {{ .Env.STATSD_ENDPOINT }}
                prefix: "cadence-worker"
        {{- else if .Env.PROMETHEUS_ENDPOINT }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
        {{- else if .Env.PROMETHEUS_ENDPOINT_3 }}
        metrics:
            prometheus:
                timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_3 }}
        {{- end }}

clusterMetadata:
    enableGlobalDomain: {{ default .Env.ENABLE_GLOBAL_DOMAIN "false" }}
    failoverVersionIncrement: 10
    masterClusterName: "master"
    currentClusterName: "master"
    clusterInformation:
        master:
            enabled: true
            initialFailoverVersion: 0
            rpcName: "cadence-frontend"
            rpcAddress: {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7933

dcRedirectionPolicy:
    policy: {{ default .Env.DC_REDIRECT_POLICY "selected-apis-forwarding" }}
    toDC: ""

archival:
  history:
    status: {{ default .Env.HISTORY_ARCHIVAL_STATUS "disabled" }}
    enableRead: {{ default .Env.HISTORY_ARCHIVAL_ENABLE_READ "false" }}
    provider:
      filestore:
        fileMode: {{ default .Env.HISTORY_ARCHIVAL_FILE_MODE "" }}
        dirMode: {{ default .Env.HISTORY_ARCHIVAL_DIR_MODE "" }}
  visibility:
    status: {{ default .Env.VISIBILITY_ARCHIVAL_STATUS "disabled" }}
    enableRead: {{ default .Env.VISIBILITY_ARCHIVAL_ENABLE_READ "false" }}
    provider:
      filestore:
        fileMode: {{ default .Env.VISIBILITY_ARCHIVAL_FILE_MODE "" }}
        dirMode: {{ default .Env.VISIBILITY_ARCHIVAL_DIR_MODE "" }}

domainDefaults:
  archival:
    history:
      status: {{ default .Env.DOMAIN_DEFAULTS_HISTORY_ARCHIVAL_STATUS "disabled" }}
      URI: {{ default .Env.DOMAIN_DEFAULTS_HISTORY_ARCHIVAL_URI "" }}
    visibility:
      status: {{ default .Env.DOMAIN_DEFAULTS_VISIBILITY_ARCHIVAL_STATUS "disabled" }}
      URI: {{ default .Env.DOMAIN_DEFAULTS_VISIBILITY_ARCHIVAL_URI "" }}

kafka:
    tls:
        enabled: false
    clusters:
        test:
            brokers:
                - {{ default .Env.KAFKA_SEEDS "" }}:9092
    topics:
        cadence-visibility-dev:
            cluster: test
        cadence-visibility-dev-dlq:
            cluster: test
    applications:
        visibility:
            topic: cadence-visibility-dev
            dlq-topic: cadence-visibility-dev-dlq

publicClient:
    hostPort: {{ default .Env.BIND_ON_IP "127.0.0.1" }}:7933

dynamicConfigClient:
    filepath: {{ default .Env.DYNAMIC_CONFIG_FILE_PATH "/etc/cadence/config/dynamicconfig/development.yaml" }}
    pollInterval: "60s"

blobstore:
  filestore:
    outputDirectory: {{ default .Env.FILE_BLOB_STORE_OUTPUT_DIRECTYORY "" }}
